### PR TITLE
Add addw2

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by jackpot51** [comment]
@leviport please verify addw1 backlight functionality with this change

**Comment by jackpot51** [comment]
#6 may make this obsolete

**Review by leviport — APPROVED** [review]

**Comment by leviport** [comment]
Looking at https://github.com/pop-os/gnome-settings-daemon/pull/6 next

**Comment by jackpot51** [comment]
Fixed by #6

**Pull request closed without merging**
